version: '3.9'

services:
  db: 
    # ports:
    #   - '5432:5432'
    image: postgres
    # volumes:
      # - ./data/db:/var/lib/postgresql/data
    environment:
      # - "POSTGRES_HOST_AUTH_METHOD=trust" 
      - POSTGRES_DB = postgres
      - POSTGRES_USER = root
      - POSTGRES_PASSWORD = Postgres_123123
    # hostname: db
  web:
    # restart: always
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment: 
   
      - POSTGRES_NAME = postgres
      - POSTGRES_USER = root
      - POSTGRES_PASSWORD = postgres
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT = 5432

    depends_on:
      - db


